experiment_id: test-whisper-01
model:
  name: "whisper"
  dir: "./models/local/models--Systran--faster-whisper-small"
input:
  audio_glob: "/Users/ac/main/amia2025-stt-benchmarking/data/audio/testing/*.mp3"
  duration_sec: 120
  sample_rate: 16000
output:
  dir: "outputs/testing/whisper"
wandb:
  project: amia-stt
  group: pilot-whisper-test-01
  tags: ["whisper_test"]